numbers = [5, 2, 4, 7, 1, 2, 3, 6, 9, 7, 8]
print(numbers.count(2))
print(numbers.index(7))
# For checking index of certain number we can also use 'in'
print(9 in numbers)
print(numbers)
numbers.pop()
print(numbers)
numbers.sort()
print(numbers)
numbers.reverse()
print(numbers)
numbers.append(13)
print(numbers)
numbers.remove(2)
print(numbers)
numbers.insert(0,0)
print(numbers)
nums2 = numbers.copy()
print(nums2)